### ISSUE TITLE
simple admin / login with email,pass

### ISSUE THREAD

**Issue by uptownhr** [uptownhr/blog#2]

**Comment by AlexRex** [comment]
Need to login users? Or just the first time they install the app?

**Comment by uptownhr** [comment]
For the time being, lets do login based on the config.admin = { user:'admin', pass: 'test' }

**Comment by AlexRex** [comment]
Now you only can use `{ user:'admin', pass: 'test' }` to login. See file `config>passport.js` and modify the code again for having it working with db users.
