### ISSUE TITLE
Change slug: Problem with same ID

### ISSUE THREAD

**Issue by AlexRex** [uptownhr/blog#6]
The actual slug is like: \`localhost:2000/story-title#id\` So if we have two stories with the same title: \_story-github\_, for example and we're currently viewing that story our url would be: \`localhost:2000/story-github#ID\` And we want to access from the menu to our other story that its called identically \_story-github\_, so the browser interprets that we're navigating from one anchor to another one in the same page, because the unique thing that changes is the #ID.

**Comment by AlexRex** [comment]
Also, when looking in the database for the SLUG received, we retrieve the first one, so we're always looking for the last updated in the db.

**Comment by uptownhr** [comment]
lets put this bug on hold for now. I believe we can address this by making the slug unique when the story is created
